{% set name = "cdasws" %}
{% set version = "1.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdasws-{{ version }}.tar.gz
  sha256: 25099d0ef4e6a4c17b0520c3938b4e238489a3e4034f6ce0da43ed3fd962519e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python {{ python_min }}
    - python-dateutil >=2.8.0
    - requests >=2.20
    - urllib3 >=1.24.1

test:
  imports:
    - cdasws
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://cdaweb.gsfc.nasa.gov/WebServices/REST
  summary: NASA's Coordinated Data Analysis System Web Service Client Library
  license: NOSL
  license_file: NASA_Open_Source_Agreement_1.3.txt

extra:
  recipe-maintainers:
    - candeynasa
    - ericthewizard
    - berniegsfc
